### ISSUE TITLE
OIDC Standard Claims Support

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1352]
ref: #260 

[Specification of OIDC Standard Claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)

Standard attributes to be supported:
| standard attributes     |                                                               | Filled from SSO/Login ID | Edit by Admin | Edit by End-user |
|-------------------------|---------------------------------------------------------------|--------------------------|---------------|------------------|
| given\_name             |                                                               | Yes                      | Yes           | Yes              |
| family\_name            |                                                               | Yes                      | Yes           | Yes              |
| email                   | Populated from identity,  user can set which one is Preferred | Yes                      | via identity  | via identity     |
| email\_verified         |                                                               |                          |               |                  |
| birthdate               |                                                               |                          | Yes           | Yes              |
| zoneinfo                |                                                               |                          | Yes           | Yes              |
| locale                  | Available values are set in Localization                      |                          | Yes           | Yes              |
| phone\_number           | Populated from identity                                       | Yes                      | via identity  | via identity     |
| phone\_number\_verified |                                                               |                          |               |                  |
| updated\_at             |                                                               |                          |               |                  |

**Notes:**
- Email may be provided by multiple identities, end-users should be able to set one as primary/preferred for the email claims
- If the claims are disabled by the Admin, the end-users will not be able to see/edit them in AuthUI Settings

**Todo:**

Design task: #1389 
- [ ] Design: **Profile** Page in AuthUI Settings
- [ ] Design: In Portal, update **User Details** page to show the claims
- [ ] Design: In Portal, a new page to config the claims

Implementation:
- [ ] update openid-configuration claims_supported
- [ ] Read/Write/Config with Admin API
- [ ] Return in UserInfo
- [ ] Show, Edit, Config in Web Portal for Admin
- [ ] Show and Edit in AuthUI Settings for End-users

**Comment by fungc-io** [comment]
- Implement a webhook to notify the admin that an end-user’s claims have been updated.
- Tenant admin can disable the claims if they want to use their own user management system. Then the profile settings will not be visible to the end-users.
- Names, gender and birthdate can be populated from Identity Providers. Provide options for admins to choose if these claims will sync every time the end-users sign in. If they are synced, such attributes shall not be modified manually.
- We may need to introduce the concept of “Primary IdP” to handle the sync when an end-user has multiple IdPs connected.
