### ISSUE TITLE
Minimal User Setting Page Main Page

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#144]
Plan for & Develop the minimal user setting page, doesn't require all features/information, and could be read-only first.

**Comment by chpapa** [comment]
2nd thought... maybe we already have the minimal actually?

**Comment by louischan-oursky** [comment]
# Milestone of 2020-08

- [ ] Align existing pages (26 page in total) with the latest design
- [ ] `Security`
  - [ ] Primary authenticator (Read Only)
    - [ ] Password
    - [ ] OOB OTP
  - [ ] Secondary authenticator (Read Only)
    - [ ] TOTP
    - [ ] OOB OTP
    - [ ] Password
  - [ ] Recovery code
- [ ] `/settings/recovery_code`
  - [ ] List recovery code
  - [ ] Download
  - [ ] Regenerate

# Future

- [ ] `Connected Identities`
  - [ ] List most recently add 3 identities
  - [ ] Show all button
- [ ] `/settings/authenticator/totp`
  - [ ] List TOTP authenticator
  - [ ] Add button
- [ ] `/settings/authenticator/oob_otp`
  - [ ] List OOB OTP authenticator
  - [ ] Add button
- [ ] `/settings/change_password`
  - [ ] Password policy
- [ ] Revoke all device tokens
- [ ] `Recent Sessions`
 - [ ] Show most recent 3 sessions
 - [ ] Show all button
- [ ] `/settings/session`
  - [ ] List session
  - [ ] Revoke one button
  - [ ] Revoke all button
