### ISSUE TITLE
Minimal Web Portal

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#145]
Plan / Design A minimal Web Portal that can:

- Interact with Admin API (maybe list all users?)
- Save / Export a Authgear Server config (maybe disable/enable anonymous user?)

**Comment by louischan-oursky** [comment]
# Overview

The portal consists of a web frontend and a backend server.
It is distributed as a Docker image.

# Operation mode of the portal

Here are the 2 operation modes supported by the portal.

## Self-hosted Authgear and portal

- Suppose `mycompany.com` is a domain owned by our compnany. It is shared by many projects.
- `myapp.mycompany.com` is the host of our application server.
- `accounts.myapp.mycompany.com` is the host of the Authgear acting as the authentication server of our application server.
- Authgear hosted on `accounts.myapp.mycompany.com` must set `Domain` attribute of the cookies it writes to `myapp.mycompany.com`.
- `myapp-admin.mycompany.com` is the host of the portal backend.
- `accounts.myapp-admin.mycompany.com` is the host of the Authgear acting as the authentication server of the portal backend.
- Authgear hosted on `accounts.myapp-admin.mycompany.com` must set `Domain` attribute of the cookies it writes to `myapp-admin.mycompany.com`.

In this setup, the developer needs to deploy 1 instance of Authgear.
That instance of Authgear serves 2 tenants: 1 tenant for the application, 1 tenant for the portal.
Since there are 2 tenants, the set of users are **COMPLETELY** isolated.

Both Authgear and the portal backend reads the same configuration from filesystem.
On Kubernetes, it is expected that Authgear and the portal are separate Deployments, with the same ConfigMap/Secret mounted on their filesystem.
The ConfigMap/Secret are usually managed by tools like Helm, therefore, direct write to the ConfigMap/Secret is not supported.
Instead, the portal offers an option to export the current configuration as a tarball.

The exported tarball contains all configuration and resources.
The filesystem structure looks like

```
/authgear.yaml
/authgear.secrets.yaml
/templates/auth_ui_login.html
...
```

## Cloud hosted Authgear and portal

- Suppose `authgearapps.com` is the domain of the cloud hosted Authgear.
- `myapp.authgearapps.com` is the host of a particular tenant of Authgear.
- `myapp.authgearapps.com` is the host of the Authgear acting as the authentication server of some external application server.
- Authgear hosted on `myapp.authgearapps.com` must set `Domain` attribute of the cookies it writes to `myapp.authgearapps.com`.
- `portal.authgear.com` is the host of the portal backend.
- `accounts.portal.authgear.com` is the host of the Authgear acting as the authentication server of the portal backend.
- Authgear hosted on `accounts.portal.authgear.com` must set `Domain` attribute of the cookies it writes to `portal.authgear.com`.

In this setup, many instances of Authgear are deployed to serve `*.authgearapps.com`.
Another instance of Authgear is deployed to serve `accounts.portal.authgear.com`.

Users of `portal.authgear.com` can manipulate ALL tenants of `authgearapps.com`, given that the user has access to that particular tenant.

Physically, everything is deployed on the same Kubernetes cluster.
The portal backend of `portal.authgear.com` reads and writes the ConfigMap/Secret of a tenant of `authgearapps.com`.

# The portal frontend

The portal frontend is a React app written in TypeScript.
It interacts with the portal backend via GraphQL.
The GraphQL client is either Relay or Apollo (TBC).

# The portal backend

The portal backend has two parts.

The first part is a GraphQL server that acts as a proxy of a particular tenant of Authgear Admin API.
For example, to serve `portal.authgear.com/apps/myapp/users`, the portal backend proxies the request to the Admin API of `myapp.authgearapps.com`.

The second part is component that communicate with Kubernetes API server to manage the tenants of Authgear.

- Create a tenant of Authgear (a.k.a. create app)
- Update a tenant of Authgear (a.k.a. view or edit configuration)
- Grant/Deny access to a tenant of Authgear (a.k.a. add or remove collaborator)
- Disable a tenant of Authgear (?)
- Delete a tenant of Authgear (?)

# Authorization in the portal

*To be specified later*

---

# Milestone of August 2020

- [ ] Setup the portal frontend (**1.5 day**)
  - Setup Parcel
  - Setup browserslist
  - Setup PostCSS
  - Setup CSS Modules
  - Setup PostHTML
  - Setup stylelint
  - Setup TypeScript
  - Setup Babel
  - Setup eslint
  - Setup GraphQL client
  - Enable Parcel v2 bundle analyzer
  - Setup development API Proxy
  - Ensure development experience is good enough (reload-after-save, etc...)
- [ ] Minimal frontend (**3 days**)
  - Delegate authentication to Authgear
  - Logout
  - Add a page to list users
  - Add a page to display AuthenticationConfig
  - Validate AuthenticationConfig
  - Export the configuration as tarball
- [ ] Setup the portal backend (**3 days**)
  - Investigate how to proxy GraphQL request to another GraphQL server.
  - Read Authgear configuration from filesystem.
  - Expose Authgear configuration via GraphQL.
  - Add a GraphQL mutation to validate Authgear configuration.
  - Add a plain HTTP endpoint to export the whole configuration as a tarball.
- [ ] CI and CD (**4 hours**)
  - Setup Github Actions
  - Test and lint the frontend
  - Test and lint the backend
  - Build a Docker image
    - Bundle the frontend as static assets
    - Build the backend as binary
    - Serve the frontend at `/`.
    - Serve the backend at `/api/`.

**Comment by chpapa** [comment]
@louischan-oursky Thanks for the planning, some questions / clarification:

> In this setup, the developer needs to deploy 1 instance of Authgear.
That instance of Authgear serves 2 tenants: 1 tenant for the application, 1 tenant for the portal.
Since there are 2 tenants, the set of users are COMPLETELY isolated.

I assume that meant when the portal need some sort of initialization when it connects with an authgear for the first time? e.g. config the tenant for the Portal itself with our own configurations (what type of login we support, MFA, our own branding for the login page, etc) Or the setup is manual?

> Instead, the portal offers an option to export the current configuration as a tarball.

If the initialization process above is auto, I assume then it is not needed as if it can configure the portal's tenant, it must be able to configure other tenant too... unless it is manual.

> In this setup, many instances of Authgear are deployed to serve *.authgearapps.com.
Another instance of Authgear is deployed to serve accounts.portal.authgear.com.

Just curious, why not also use the same instance, say `accounts.authgearapps.com` for authentication of `portal.authgear.com`? The ultimate eat your own dog food lol.

> The portal backend of portal.authgear.com reads and writes the ConfigMap/Secret of a tenant of authgearapps.com.

I'm thinking, what if we make the version of our open source 100% identical to the cloud version? So on open sources version, we will not maintain the current "simple docker image without portal", we will only have ONE set of HELM (or whatever way we deploy to our cloud k8s), so if you use open sources version, you only have one way to deploy it... It will greatly simplify our documentation and releases procedure?

**Comment by louischan-oursky** [comment]
> I assume that meant when the portal need some sort of initialization when it connects with an authgear for the first time? e.g. config the tenant for the Portal itself with our own configurations (what type of login we support, MFA, our own branding for the login page, etc) Or the setup is manual?

The setup is manual. As I mentioned in self-hosted deployment, the configuration (`authgear.yaml`, `authgear.secrets.yaml`) are usually managed by tools like Helm. The portal should not manage the configuration at all. And actually the configuration of the portal itself should also be managed by Helm-like tools.

> If the initialization process above is auto, I assume then it is not needed as if it can configure the portal's tenant, it must be able to configure other tenant too... unless it is manual.

The 1st answer should answer this question as well. The setup is manual.

> Just curious, why not also use the same instance, say accounts.authgearapps.com for authentication of portal.authgear.com? The ultimate eat your own dog food lol.

We of course are eating our own dog food because we are using authgear and the JS web SDK to build the portal! This is related to the [proposed structure of multi-tenant mode](https://github.com/authgear/authgear-server/issues/169).

The instances of Authgear serving `*.authgearapps.com` are all considered as "apps", whose configuration are managed by  `portal.authgear.com`. `accounts.portal.authgear.com` and `portal.authgear.com` are deployed by us manually with Helm. So their configuration are managed by Helm.

It sounds like what you want here is the capability similar to self-hosting compiler, in which the portal can manage the authgear tenant serving as its authentication server. It becomes a chicken-and-egg problem. To use the portal, we first need to authenticate with a tenant of authgear. To create a tenant of authgear, we first need to authenticate into the portal. Separating the two eliminates this problem. Deployment of `accounts.portal.authgear.com` and `portal.authgear.com` would be easier too.

> I'm thinking, what if we make the version of our open source 100% identical to the cloud version? So on open sources version, we will not maintain the current "simple docker image without portal", we will only have ONE set of HELM (or whatever way we deploy to our cloud k8s), so if you use open sources version, you only have one way to deploy it... It will greatly simplify our documentation and releases procedure?

We only have a single codebase. The switching of the mode/version is via configuration. Having docker image has many other usages though, like quick demo and for people to try it out very quickly. I agree if the helm configuration we use to deploy our cloud can also be used by outsider to deploy their own cloud is a great property. Let's see if we can achieve this.

**Comment by chpapa** [comment]
> It becomes a chicken-and-egg problem. To use the portal, we first need to authenticate with a tenant of authgear. To create a tenant of authgear, we first need to authenticate into the portal. Separating the two eliminates this problem. Deployment of accounts.portal.authgear.com and portal.authgear.com would be easier too.

Sounds like this "chicken-and-egg" problem could simply be solved by creating the "first admin account" in the setup script of the Cloud?

Plus a big advantage is we can use Authgear Portal itself for Authgear Cloud's user :) 

(Speaking of which it would be cool if Authgear's User Metadata to be used to store like, which app tenant and role the user have access to, then we can have our own portal admin change everything lol)

**Comment by louischan-oursky** [comment]
> Sounds like this "chicken-and-egg" problem could simply be solved by creating the "first admin account" in the setup script of the Cloud?
> 
> Plus a big advantage is we can use Authgear Portal itself for Authgear Cloud's user :)

I am thinking of also making the portal server a CLI program. When being accessing via CLI locally, authentication is somehow not needed. In addition to `authgear-portal start` which starts the portal server, there will be `authgear-portal exec` which take GraphQL query from stdin. Effectively there are two portal frontends, the web and the CLI. In the future, the CLI may support authentication and the developer can use the CLI in CI environment.

**Comment by chpapa** [comment]
@louischan-oursky so does the chicken-and-egg problem non-issue and we can use the same authgear instances for Cloud tenant and Portal? Or you still think it is better seperated? (actually I won't insist, just thought easier and asking)
