### ISSUE TITLE
User profile implementation tracking issue

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1510]
## Standard attributes

- [x] https://github.com/authgear/authgear-server/issues/1507
- [x] https://github.com/authgear/authgear-server/issues/1513
- [x] https://github.com/authgear/authgear-server/issues/1515
- [x] https://github.com/authgear/authgear-server/issues/1516
- [x] https://github.com/authgear/authgear-server/issues/1534
- [x] https://github.com/authgear/authgear-server/issues/1537
- [x] https://github.com/authgear/authgear-server/issues/1541
- [x] https://github.com/authgear/authgear-server/issues/1563
- [x] https://github.com/authgear/authgear-server/issues/1566
- [x] https://github.com/authgear/authgear-server/issues/1571
- [x] https://github.com/authgear/authgear-server/issues/1591
- [x] https://github.com/authgear/authgear-server/issues/1592
- [x] https://github.com/authgear/authgear-server/issues/1603
- [x] https://github.com/authgear/authgear-server/issues/1622
- [ ] #1824 

## Blocking webhook

- [x] #1605
- [x] #1606
- [x] #1607

## Custom attributes

- [x] #1684
- [x] #1687
- [x] #1692
- [x] #1624
- [x] #1627
- [x] #1628
- [x] #1625
- [x] #1626 
- [x] #1629
- [x] https://github.com/authgear/authgear-server/issues/1728

## Roles

- Add table `_auth_role`, `_auth_user_role`
- Add `roles` in User type in the Admin API
- Expose roles in user api model
- Expose roles in User Info endpoint
- Add `createRole`, `updateRole`, `deleteRole`, `addRoleToUser`, `removeRoleFromUser` mutation in the Admin API
- Implement display role, create role, update role, delete role, add role to user, remove role from user in the portal
- Include `x-authgear-user-roles` in the resolver endpoint response.

## Search

- Augment elasticsearch to search user by standard attributes, custom attributes and roles?

**Comment by chpapa** [comment]
Closing as #1824 should be the last one and no need tracking
