### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#155]
# Milestone of 2020-08

- [ ] Align existing pages (26 page in total) with the latest design
- [ ] `Security`
  - [ ] Primary authenticator
    - [ ] Password
    - [ ] OOB OTP
  - [ ] Secondary authenticator
    - [ ] TOTP
    - [ ] OOB OTP
    - [ ] Password
  - [ ] Recovery code
  - [ ] Revoke all device tokens
- [ ] `Connected Identities`
  - [ ] OAuth
  - [ ] Login ID
   - [ ] Verified status
- [ ] `/settings/authenticator/totp`
  - [ ] List TOTP authenticator
  - [ ] Add button
- [ ] `/settings/authenticator/oob_otp`
  - [ ] List OOB OTP authenticator
  - [ ] Add button
- [ ] `/settings/change_password`
  - [ ] Password policy
- [ ] `/settings/recovery_code`
  - [ ] List recovery code
  - [ ] Download
  - [ ] Regenerate

# Future

- [ ] `Recent Sessions`
 - [ ] Show most recent 3 sessions
 - [ ] Show all button
- [ ] `/settings/session`
  - [ ] List session
  - [ ] Revoke one button
  - [ ] Revoke all button

---

**Comment by louischan-oursky** [comment]
Duplicate of https://github.com/authgear/authgear-server/issues/144
