### ISSUE TITLE
Account deletion tracking issue

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1736]
- [x] https://github.com/authgear/authgear-server/issues/1737
- [x] https://github.com/authgear/authgear-server/issues/1739
- [x] https://github.com/authgear/authgear-server/issues/1742
- [x] https://github.com/authgear/authgear-server/issues/1753
- [x] https://github.com/authgear/authgear-server/issues/1755
- [x] https://github.com/authgear/authgear-server/issues/1757
