### ISSUE TITLE
Support WhatsApp OTP to login

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1963]
## User Stories

- As an end-user, I can use my phone number to login to Authgear by sending an OTP via WhatsApp.
- As a developer, I can send use WhatsApp to send OTP to verify a phone number and authenticate the end-user.

## Design

**Business**

We will support the use of the official "WhatsApp Business API" via Twillio.

A separate API account will be used by each tenant. The user do not need to provide their account, we will help them manage the account at the back if they subscribe to this feature. This feature is not included in the standard pricing plans, it must be manually enabled by us.

By default it has a limit of 3000 Login via WhatsApp per day.

**Login flow**

1. End-user enter their own phone number.
2. The screen will show an OTP and a WhatsApp number. With a [`wa.me`](https://faq.whatsapp.com/general/chats/how-to-use-click-to-chat/) link. e.g. `https://wa.me/1XXXXXXXXXX?text=654092`
3. The end-user send the OTP to the number using their WhatsApp account
4. The system will check if the number and the OTP match. The end-user is authenticated if they match.

In step 4, there is a button saying "Send OTP to me with SMS"
By clicking this, it will fallback to the traditional SMS OTP flow.

## Goal

Create a project for us to demo this feature.

## Appetite 

2 weeks

## Task Tracker

- Add config to phone otp authenticator #1982
    - SMS only
    - Whatsapp + SMS fallback
    - Whatsapp only
- Update interaction for whatsapp otp flow
  - [x] Update signup flow with whatsapp otp #1982
  - [x] Update add authenticator flow via settings, admin portal with whatsapp otp #1982
  - [x] Update phone verification flow with whatsapp otp #1987
  - [x] Implement whatsapp otp provider to generate and verify OTP #1990
  - [x] Update whatsapp otp page design #1995
  - [x] Update login flow with whatsapp otp #2000 
  - [x] Check promote user flow
  - [x] Refactor sms fallback using existing alternatives handler #2018
  - [x] Fix OTP is renew and won't resend during authenticator creation when switching different authenticator type #2025
  - [x] Fix switch to verification code again within 1 min will failed due to rate limit #2025
  - [x] Update to new UI #2030
  - [x] Support device token checkbox in whatsapp otp page #2031 
  - [ ] Update button with gtm event tag
  - [ ] Update copywriting in AuthUI and portal to replace the term "SMS" with "Phone" wherever appropriate
- Webhook #2003 
    - verify webhook 
    - store otp to redis store
- ~~Update portal for phone otp config~~
- ~~Allow enable whatsapp feature based on app plan~~

**Comment by fungc-io** [comment]
Need the design for step 2.
the page should include a "Continue" button in case the auto refresh didnt work

**Comment by fungc-io** [comment]
In the WhatsApp + SMS fallback case
1. check if number is registered in WhatsApp
2. If yes: Show OTP for WhatsApp, and optional to SMS; If no: show SMS OTP

**Comment by carmenlau** [comment]
- [ ] Add config to phone otp authenticator
    - SMS only
    - Whatsapp + SMS fallback
    - Whatsapp only
- [ ] Update interaction for whatsapp otp flow
    - whatsapp otp page
    - check if user's number has whatsapp
    - integrate whatsapp otp flow to signup
    - integrate whatsapp otp flow to login
    - integrate whatsapp otp flow in settings
    - proceed verification by reading otp from redis store
- [ ] Webhook
    - verify webhook 
    - store otp to redis store
- [ ] Update portal for phone otp config
- [ ] Allow enable whatsapp feature based on app plan

**Comment by carmenlau** [comment]
For checking if the phone number has whatsapp, the official api will disable the business number if we don't send.
And twillio and wati.io don't have api doesn't have this api.
So we can't check that and the whatsapp page will always be shown. Use can fallback to sms if the app enables sms fallback.

https://developers.facebook.com/docs/whatsapp/on-premises/reference/contacts
https://www.twilio.com/docs/whatsapp/best-practices-and-faqs#:~:text=Can%20I%20check%20if%20a,was%20found%20to%20be%20invalid.
https://docs.wati.io/reference/post_api-v1-addcontact-whatsappnumber

**Comment by chpapa** [comment]
In that case the design needs to be much clearer to suggest the fallbacks @fungc-io

**Comment by fungc-io** [comment]
Updated design:
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=6113%3A84428

- Move "QR code/open in whatsapp" button to the next step
- Changed "I've sent the code" to a smaller "refresh" button to make it cleaner
- Changed "Redirecting" screen
- Added context for whtatsapp OTP as secondary authenticator

To be discussed:
- @carmenlau mentioned that the auto-refresh may stop working because of the battery saving features of device, and therefore must include a manual trigger to verify the webhook. Can we trigger the verification when the app is in focus again? so we can reduce the chance that needs manual trigger by the users
- QR code to be shown in a Modal or in the original pane? 
I personally prefer modal, because it looks better and more streamlined to understand,
