### ISSUE TITLE
Redesign the native SDKs

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1971]
**Problem**

The native SDKs and React Native SDK were developed independently and do not share code, making it hard to maintain.

As Flutter and Xamarin SDKs are planned in the roadmap, and they will be implemented by wrapping the native SDKs. 
It's a good opportunity for us to build it right, so we can reduce the maintenance and development effort in the future. 

**Todo**

Build the native SDKs as a core to be extended to cross platform SDKs including React Native, Flutter, Xamarin

- [x] Research Xamarin: Done in https://github.com/authgear/authgear-server/issues/1744
- https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationParameters(int,%20int)
- https://developer.apple.com/documentation/localauthentication/accessing_keychain_items_with_face_id_or_touch_id
- [ ] Research Flutter: https://github.com/authgear/authgear-server/issues/1972
- [x] Research React Native
  - React Native native module is natively written in Objective-C. Using calling Swift from Objective-C requires the generation of -Swift.h header. However, I cannot get that setup properly when the native module is a dependency.
- [ ] Create a new repository for the experimental SDKs
- [ ] Extract Authgear Core for iOS written in Swift
- [ ] Extract Authgear Core for Android written in Java
- [ ] Rewrite React Native SDK with Authgear Core
- [ ] Write Xamarin SDK with Authgear Core
- [ ] Write Flutter SDK with Authgear Core
- [ ] Documentation for each SDK

**Comment by louischan-oursky** [comment]
We decided to maintain each SDK separately. This issue is no longer relevant.
