### ISSUE TITLE
Implement Xamarin SDK

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1974]
**Todo**
Create a Xamarin SDK targeting iOS and Android.

The SDK should support:
- open the webview for login/signup, settings, logout
- manage the tokens
- send requests with token
- Biometrics authentication

**Items**
- [x] Create new repo https://github.com/authgear/authgear-sdk-xamarin
- [x] SDK
- [x] Docs https://authgear.github.io/authgear-sdk-xamarin/
- [x] Demo app
- [x] Update Marketing Website

**Extended goal**
Build for Windows app as a target

**Comment by fungc-io** [comment]
I can't find the Android demo app on appcenter

I've tested on the iOS demo app,
Most features work,
But the "Use TransientTokenStorage" seems not working.

**Steps**
1. Setup a biometric login then logout
2. Enable ""Use TransientTokenStorage" 
3. Click Configure
4. "Authenticate Biometric" to login
5. Quit the app
6. Reopen the app
7. See "<no-authgear-instance>"
8. Click "Configure" again
9. The app shows "Authenticated" without asking me to login

**Comment by louischan-oursky** [comment]
https://appcenter.ms/orgs/Oursky/apps/Authgear-Demo-Xamarin-Android
https://appcenter.ms/orgs/Oursky/apps/Authgear-Demo-Xamarin-iOS

**Comment by fungc-io** [comment]
The "Use TransientTokenStorage" is also not working on android. 
It shows an error message when "Configure" is tapped
```
System.Collections.Generic.KeyNotFound
Exception: The given key 'default' was not
present in the dictionary.
...
```

**Comment by fungc-io** [comment]
Checked, the "Use TransientTokenStorage" is working on both android and ios
