### ISSUE TITLE
Self-serve subscription

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2047]
## Goal / User stories

- As a user, I can subscribe to Authgear service through the portal by myself
- ~As a dev, I can know the usage of each user, assign usage quotas to a user easily~

## Features

Enabling/disabling certain features for individual users is supported already.

What we are missing:
- Quota system for usage based features
  - SMS, WhatsApp OTP, MAUs
  - A soft and hard limit for each tenant should be implemented
- Billing system integration: Stripe
- Metered billing

WhatsApp and SMS are shared account by default. If the users want a dedicated account, they should always contact us for manual set up.

## Implementation Notes

To speed up the launch, pre-built UI from Stripe is preferred if available, which includes:

- Checkout page: https://stripe.com/docs/billing/quickstart
- Billing portal: https://stripe.com/docs/billing/subscriptions/integrating-customer-portal?platform=billing
- Invoicing (email communication)

## Appetite

3 weeks

### Research
- [x] #2048
- [x] Research on Stripe API and metered billing
  - [x] #2051
  - [x] #2043 
- [x] #2050

### Portal UI changes
- [x] #2049
- [x] #2044 

### Implementation

- [x] https://github.com/authgear/authgear-server/issues/2077
- [x] https://github.com/authgear/authgear-server/issues/2078
- [x] https://github.com/authgear/authgear-server/issues/2083
- [x] https://github.com/authgear/authgear-server/issues/2086
  - [x] Create the `_portal_usage_record` table
  - [x] Add command to aggregate active user count into `_portal_usage_record`
  - [x] Add command to aggregate sms count by region into `_portal_usage_record`
  - [x] Add command to aggregate email count into `_portal_usage_record`
  - [x] Add command to aggregate whatsapp otp success count into `_portal_usage_record`
  - [x] https://github.com/authgear/authgear-server/issues/2124
- [x] https://github.com/authgear/authgear-server/issues/2144
- [x] https://github.com/authgear/authgear-server/issues/2148
- [x] Stripe Integration
  - [x] https://github.com/authgear/authgear-server/issues/2104
  - [x] https://github.com/authgear/authgear-server/issues/2106
  - [x] https://github.com/authgear/authgear-server/issues/2123
  - [x] Setup Stripe account for development
  - [x] Subscribe to a plan
    - [x] ~~Pre-create the Stripe Customer for an account/a project (TBC)~~ Customer is created during the checkout process per project
    - [x] https://github.com/authgear/authgear-server/issues/2115
    - [x] #2120
    - [x] #2118
    - [x] #2119
    - [x] #2143
  - [x] https://github.com/authgear/authgear-server/issues/2134
  - [x] https://github.com/authgear/authgear-server/issues/2152
  - [x] Tell the developer that they have to contact us to cancel subscription
  - [x] Tell the developer that they have to contact us to switch plan
  - [x] Deployment
      - [x] Update helm chart to configure redis for cache
      - [x] Update helm chart to have cronjob to run commands 
(to be discovered...)

**Comment by fungc-io** [comment]
Only the Billing page is needed to be updated in the Portal to enable subscription.
The user flow for signup should remain the same for now.
The existing feature blocks and CTA to billing page do not need changes

Add affordance so that the billing page allows the user to:
- Check their current metered usage (SMS, WhatsApp, MAU)
- Check their current plan details
- Look at upgrade options, the plan details
- Switch (upgrade/downgrade) plans
- View/Change billing details (use Stripe billing portal)
- View past invoices (use Stripe billing portal)

**Comment by fungc-io** [comment]
UI Design in Figma:
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=6238%3A97184

**Comment by chpapa** [comment]
Quick comment on the design:

1. On `Billing Page (with page title)`
    1. for the usage bar of `Monthly Active User`, it should have a normal, warning, and over-usage state
    2. I don't think it make visual sense to show SMS and Whatsapp as a full bar (we don't have limits of it)
    3. It's nice to show how each bar affect the bill (e.g. 34,512 MAUs meant +USD 50, 165,000 SMS meant how much SMS? etc)
    4. Align the button of "Downgrade" horizontally

**Comment by saigaai3** [comment]
Updates on UIUX

- Figma Link (Subscription Page): https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=4997%3A43574
- Button + Modal components now following Microsoft Fluent UI 
  - **Components were not link to the official Microsoft Fluent Web Figma file directly
    - If the Microsoft designer published a new file instead updating the current file, we are doomed
    - It was so old that they didn’t even add variants for components 
    - Current approach: Copy instance from Fluent file →  Detach → Re-component in Authgear file
- Section Containers are now fully responsive with width constraints, there are 2 ways to manage responsiveness:
  - Limit Section Containers width
    - Minimum width = 980
    - Maximum width = 1252
  - Limit Main Container position constraints:
      - Main Container Minimum width = 1028
      - Main Container Maximum width = 1300
      - When Main Container width is between 1028 <> 1300 → Constraints = Top + Left and Right
      - When Main Container width is ≤1028 or ≥1300 → Constraints = Top + Left
- Price Plan Card CTA button aligned with optional padding
  - Applicable to Developers + Startups plan for now
- Additional MAU, SMS and WhatsApp usage + estimated cost now in display
- Added Enterprise upsell modal (Email instructions)
- Added “over-limit” state to MAU metered usage
- Change tag (most popular) to “recommended” (stronger push)
- Updated Developer/ Designer Guidelines in Figma file

**Comment by saigaai3** [comment]
Updates on UIUX

- Usage of WhatsApp Authentication, SMS and Additional MAU now representing in Tooltip, alongside with clarifications on Total Cost and MAU usage update frequency

**Comment by fungc-io** [comment]
@louischan-oursky @carmenlau 
added portal design to include
- next billing date
- past month MAU
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=6304%3A97848
