### ISSUE TITLE
Improve "Application" setup flow

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2103]
## Problem
The application set up is not intuitive and users often get confused by the instructions.
The goal of this change is to simplify the setup for common usage and provide better copywriting to explain the config.

## Solution
- Introduce "Application Type", this translates to token or cookie based behind the scene. Different options are shown based on the type.
- Move Allowed Origins to per application level, group together with redirect URIs & post logout redirect URIs
- Collapse "Cookie Session Settings" as an advance setting
- Change copy `Invalidate ... after idling` -> `Expire after idling` and `... Idle Timeout` -> `Idling Lifetime`
- See below for detailed copy writing changes

### Breadboard:
![Anth gear Applications](https://user-images.githubusercontent.com/15207470/173523599-91ab612b-a136-4141-a7f4-28e2f71ab074.png)

### Copywriting
----
# Applications Page

`Description`: Configure applications to use this project as authentication.

## Advanced Cookie Settings

`Description`: Configure the cookie session settings for (domain). If you only use token-based authentication, you can simply ignore this section.

- (toggle) Persistent cookie
  - `Description:` The cookie persists after the browser is closed
- Cookie Lifetime
  - `Description:` The cookie session will expire after the lifetime
- (Toggle) Expire after idling
  - `Description:` The cookie session will expire after the idling lifetime
- Idling Lifetime
  - `Description:` The idling lifetime of a cookie

# Create Application Page

- Application Name
- Application Type
    - Native App
    - SPA
    - Traditional Web Application (Cookie based)

# Application Details Page

- Basic Info
    - Name
    - Client ID (Copy Btn)
    - Application Type
- URIs
    - Authorized Redirect URIs
        - `Description:` After users are authenticated, users will be redirected to these URI. They should include the protocol like `http://`,`https://`, or custom URI scheme for native clients.
    - Post Logout Redirect URIs (only when app type = Traditional Web Application)
        - `Description:` Users will be redirected to this path after they have logged out.
    - Allowed Origins
      - Description:` Configure cross-origin resource sharing (CORS), allowing authentication requests from these domains.
- Access Token (only when app type = SPA / Native)
    - Access Token Lifetime
        - `Description:` The `access_token` will expire after the lifetime.
    - (Check box) Issue JWT as access token
- Refresh Token (only when app type = SPA / Native)
    - Refresh token Lifetime
        - `Description:` The `refresh_token` will expire after the lifetime, after which the refresh token can not be used. This is the maximum session lifetime, the user will be logged out when the refresh token expires.
    - (Checkbox) Expire after idling
        - `Description:` The `refresh_tokn` will expire after the idling lifetime, after which the refresh token can not be used.
    - Idling Lifetime
        - `Description:` The idling lifetime of a `refresh_token`

## Todo
- [ ] Update "Applications" page
- [ ] Update "Create Application" page
- [ ] Update "Application Details Page"
- [ ] Implement Application "Quickstart Wizard"
- [ ] Hide Allowed Origins Config and derive from URLs automatically
- [ ] Move Cookie Lifetime to Advanced

**Comment by fungc-io** [comment]
@louischan-oursky @carmenlau 
I'm not sure if moving "Allowed Origins" to per application level will be a technical concern. 
I think it's easier to understand than setting this globally while other URIs are per app.

**Comment by chpapa** [comment]
Note to self: don't forgot to put Endpoint URL at the Application setup screen as well, coz most of the time developers would need Client ID, endpoint URL together for configurate

**Comment by carmenlau** [comment]
For the allowed origins settings, Auth0 allows all the callback urls automatically and developers can add additional origins to the list through application settings.

Still not sure what usecase will need to add additional allowed origins, so we prefer keep the config and hide it from the portal. So when user requests, we can just bring it back to the portal.

Todo:
1. Keep allowed origins config, remove allowed origins setting from the portal
1. Update server to allow all applications' callback urls and the allowed origins config

ref: https://auth0.com/docs/get-started/applications/set-up-cors#configure-cross-origin-authentication

Thoughts?

**Comment by fungc-io** [comment]
looks good, let's do that

**Comment by carmenlau** [comment]
it looks good to me!!

**Comment by fungc-io** [comment]
@andychow326 can help fix this?
![Screenshot 2022-07-29 at 15 46 52](https://user-images.githubusercontent.com/15207470/181710862-d86323f2-c1cc-4890-9c9c-a7a36865bbb5.png)

keep a 16px distance between command bar and the pane

**Comment by fungc-io** [comment]
2 things in the "New Application" page

- give a default name when creating a new application
![Screenshot 2022-07-29 at 15 49 14](https://user-images.githubusercontent.com/15207470/181711125-181a922b-76df-4b86-88af-119985defae6.png)

default = "My App"

- Loading state of creating
The Save button should be disabled and show with spinner. (c.f. confirm deletion modal)

@andychow326

**Comment by fungc-io** [comment]
@andychow326 
Under SPA type
- Authorized Redirect URIs
The copy is not updated according the sdk yet.
Change it to:
> After users login, users will be redirected to these URIs. Call the finishAuthentication() method in your code to complete the authentication.

**Comment by fungc-io** [comment]
@carmenlau 
i wanna test adding this screen to the flow:
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=6889%3A103866

**Comment by joyzoursky** [comment]
@fungc-io Do we have issue to update the doc site as well? It may be incorrect after the flow change (all the SDK setup pages)

**Comment by joyzoursky** [comment]
@fungc-io Below is my experience and problems faced when trying to create a "Traditional Web Application", not sure if it would also happen on others but you may take a reference.

When I fresh created an app, selecting "Traditional Web Application", and tries to configure on the demo web app link directly (Authorized Redirect URIs not yet set), it throws an error and cannot continue.

Then I guessed that I first needed to add Allowed Orgin for the app, and also the Authorized Redirect URI. However on the portal, I could only find the Authorized Redirect URIs section, **but could not find any section for Allowed Orgin**, which confused me if I should need to find the section somewhere to fix the problem before I try again. 

i.e. I didn't know that the Allowed Origin is actually auto-derived from the Authorized Redirect URIs until I found this issue. So as I thought I hadn't completed my fix, it took me some time to look for the section here and there, until I gave up finding for it and tried again with only Authorized Redirect URIs added.

**Comment by joyzoursky** [comment]
Also some minor typo on the new application page
<img width="400" alt="Screenshot 2022-08-03 at 10 34 27 AM" src="https://user-images.githubusercontent.com/12539486/182512278-f47c1840-946e-493b-b884-0698dc235dbd.png">

- later.me -> later.
- ApplicationType -> Application Type
- framework -> frameworks

**Comment by fungc-io** [comment]
@joyzoursky 
Thanks for your feedback! 👍 
The Allowed Origin is changed to auto-derive, but we havnt update the doc yet. 
Coz Allowed Origin is still required in the production, and we dont hv a staging version of docs.
