### ISSUE TITLE
WebAuthn tracking issue

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2217]
- [x] https://github.com/authgear/authgear-server/issues/2221
- [x] https://github.com/authgear/authgear-server/issues/2224
- [x] https://github.com/authgear/authgear-server/issues/2226
- [x] https://github.com/authgear/authgear-server/issues/2232
- [x] https://github.com/authgear/authgear-server/issues/2242
- [x] https://github.com/authgear/authgear-server/issues/2292
- [x] https://github.com/authgear/authgear-server/issues/2296
- [x] https://github.com/authgear/authgear-server/issues/2298

**Comment by fungc-io** [comment]
UX design for reference in Figma: https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=6752%3A101280
