### ISSUE TITLE
Ethereum Tracking Issue

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2285]
- [x] Microservice for scanning contract
    - [x] Setup crawling service
        - [x] Immediate
        - [x] 5 mins interval
        - [x] Initialize database 
        - [x] Initialize redis 
     - [x] Setup API server
         - [x] contract registration/deregistration 
         - [x] list token under collection
         - [x] get available token for an address
    - [x] Dockerize service
- [x] Integrate logic to authgear
    - [x] Implement SIWE identity CRUD
    - [x] Setup SIWE Identity
    - [x] Configure SIWE on/off
    - [x] Configure NFT collections
    - [x] #2427

**Comment by fungc-io** [comment]
@hochiw 
Can you share the contract addresses for testing in this issue?

**Comment by hochiw** [comment]
- Ethereum Mainnet
    - ERC721
        - 0xaEA4fA9451f527D5F36e65f833d88dbB56a0c264 (Be VEE - Summer Collection) 
        - 0xB16dfd9AaAF874FCb1dB8a296375577c1bAa6F21 (Nyolings) 
        - 0x62cBa733C441e914631CAD4782032481B2d8e548 (Renga Ape Yacht Club) 
        - 0x7Bf58c46d3e9316A65FE8E890CE477dd7eE988B1 (SEC Ape Yacht Club) 
        - 0x92324A569fa793485b44DA60b6663a8Cb8fC49A9 (GWEI GUYS) 
        - 0xfE58Fc763Ba915013AeE93c6f0890bFDdBe03608 (Beep Boop Botz) 
        - 0x4Cb661C12B642e43F544F09AdD3bb6dDE14554e9 (The Bearsons) 
        - 0xdF3a5f8576a6Ff359990688d94cf9c74245607f3 (GardenLockdown) 
        - 0x6678dB39984abbEF5489735c277564C5b7b9835D (Dead Will Rise) 
        - 0xe9a142CD2E34bb248c3AAC8976A541110a4e981a (The XEN NFT)
    - ERC1155
        - 0xaEA4fA9451f527D5F36e65f833d88dbB56a0c264 (Opensea Shared Storefront) (Large collection)
        - 0xc36cF0cFcb5d905B8B513860dB0CFE63F6Cf9F5c (raw contract) 
        - 0x76BE3b62873462d2142405439777e971754E8E77 (parallel) 
        - 0x2923c3e5A0F10bc02d8c90287b2Af45Cd579dEc4 (BAP UTILITIES) 
        - 0xe9d26ddCcF4007c322bD05445971C8023D5e6897 (J-WAVE MAP vol.2) 
        - 0xf85906f89aecA56aff6D34790677595aF6B4FBD7 (Liquid Artifacts) 
        - 0xd07dc4262BCDbf85190C01c996b4C06a461d2430 (Rarible) 
        - 0x03a980C83Bb58838298EA7689D9D4D22AAd51599 (Genesis Merchant Company Employee Badge) 
        - 0x47DA053384Abd2EE2bf4883927e7e1dcc3f5f95b (Genesis Merchant Company Supply Drop)
- Goerli
    - ERC721
        - 0x01B5BBDC702cA17F6F2F08AFDfe4856366361d27(Custom)
        - 0xe0abdb390ce6bead04c5f1bf82ccfd6026fbbb7d(CloneNFT)
        - 0x3f80f551459440524caec9fce97ffb4b3f6bffc0(Masa Identity Name)
        - 0x72e6b7b0ce34e5a3ca9c05f88eae2c02c895d481(DNA by Animeme Labs)
        - 0x5722eda3fab030b042c1656b255fca5412b78979(Testing MM)
        - 0x788E3D4921E37fc6a04B9EE5ECA3933929346771(Devcon VI Suit Up Collection)
        - 0x5280DA1F82649Af74Fe2D9A3d73Fe22F8b0F304B(MQBC1155)
        - 0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b(MultiFaucet NFT)
        - 0x68B99E1f800676B3E8CAFd6E9EC41BB141206740(NRJJungleVIBES)
        - 0x46bef163d6c470a4774f9585f3500ae3b642e751(Blockies)
    - ERC1155
        - 0xf4910c763ed4e47a585e2d34baa9a4b611ae448c (Opensea Shared)
        - 0xd05768845d6e9d9b5dc98a1d8c65c690dce6139d (SimpleERC1155)
- Polygon Mainnet
    -  ERC721
        - 0xB2435253C71FcA27bE41206EB2793E44e1Df6b6D (PlanetIX) 
        - 0x5D666F215a85B87Cb042D59662A7ecd2C8Cc44e6 (Galaxy OAT) 
        - 0x4d544035500D7aC1B42329c70eb58E77f8249f0F (League of Kingdoms ITEM) 
        - 0xdC3a1D0DB41D9CBc43abb61eE627d675f3730b2B (CargoX Document) 
        - 0x8a40cD9f7AbeDf96E7C1ac54723b9061A215364C (STRIKER) 
        - 0x53a0018f919bde9C254bda697966C5f448ffDDcB (EDNS) 
        - 0x5b644CD6B5282e6523c6627df27eB9352B1d7F4B (Blade City Runners) 
        - 0xd8a06936506379dbBe6e2d8aB1D8C96426320854 (Bomber Hero) 
        - 0xb4D4Cc1D867D2Ce47B8a4fbF0D1B67936eBE1E79 (GodsUnchainedXPersona) 
        - 0x667DC5619390AD150128f891C393F336457Bc53c (lensbeats.lens-Collect-32)
    -  ERC1155
        - 00x2953399124f0cbb46d2cbacd8a89cf0599974963 (Opensea Shared) (Large Collection)
        - 00x4E11Cb274981ab1D8Fce2A32d22975690A2F6deC (Dispatch-Messaging-MATIC) 
        - 00x631998e91476DA5B870D741192fc5Cbc55F5a52E (Skyweaver) 
        - 00x3376C61c450359d402F07909Bda979a4c0e6c32F (Planet IX - Gravity Grade)
- Polygon Mumbai
    -  ERC721
        - 0x037965dF7342A9dcca64EdE4EE3FE92007A58Da6 (MetaCare NFT [BT]) 
        - 0x8E492EE9C6902F0cD63FA7dCe0e432D44dCCC8fc (Ghost Hero Item) 
        - 0x74bE4C950c7f83edbFE0717575C7770b8f6A67ba (Metacare NFT Beta-Test) 
        - 0x108D88457FC04e74fc84D359d8F328c3E9b6762F (AAMA 10th dev 002) 
        - 0xc6Fe38B5411f0D972E73055CAD74Ec1AbC8379D2 (DHB Fight Club) 
        - 0xff8444dFD95709cd86240b3617D61921d551765B (GOTCHI HEROES PACK) 
        - 0xCEa34FA634f6991DCF746047855D06b7326b979b (Savanna Equipment) 
        - 0x6Ce21207F301bd17EC9A24E8A53d3c3Df6F0FFF2 (Testando) 
        - 0x427f23232a2444AFeee67e6F10A21150357A7a49 (Metacare)
    -  ERC1155
        - 0xd8c76a9c5c1df47acdd17563fd1816d969be7875 (Phi Free Object)
        - 0xA51cAdd0b41E136A6823153783e1D5Cbd7e19079 (DropShopNFTERC1155)
        - 0x4dC1465E7Bb48230fB46c2F0bf58c009275142Bc (Dispatch-Messaging)
        - 0x2F33B8870f86B319258380377076147a59E29135 (Phi Quest Object)
        - 0xc2632E3Aafc50D719Cc5e03f26dAa795641b51A6 (Test LE)
        - 0xeBDe359Af7b1c6a1c325d72F0B4aDBE8b9BD7B6D (Anxious Skulls)
        - 0x81cfBE7B73b27bfe95ba2c44Ef373AAFac6dBa3a (Carv Achievements)
        - 0x27DFfd9016829885712810671db56941B97f6C46 (Ottopia Item)

**Comment by fungc-io** [comment]
@hochiw 

The portal is stuck when adding 
0xB2435253C71FcA27bE41206EB2793E44e1Df6b6D (PlanetIX) from Polygon Mainnet
to the collection.

After ~1min it timeouted and says Service Unavailable.
![image](https://user-images.githubusercontent.com/15207470/198516147-8dc1aa9a-566f-4b97-981e-bc6281e1a940.png)

Some other collections are working

**Comment by fungc-io** [comment]
If it's because of unknown problem in Alchemy API: 
1. Shorten the timeout to 30 seconds
2. Show a dialog saying:
> ## Contact us 
> 
> The collection you entered cannot be added.
> Please contact us if this is the contract you want to use it in your project.
> 
> [Contact us] [Cancel]

**Comment by fungc-io** [comment]
The problem mentioned above is fixed by @louischan-oursky in a separate issue https://github.com/authgear/authgear-server/issues/2618
