### ISSUE TITLE
[Pitch] Authentication Setup tracking issue

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2408]
## Problem

The authentication setting UX design is not user-oriented. Design consideration:
- The portal should help the users to setup common use cases quickly. 
- The options shown should be relevant and easy to find.
- The user can navigate to the correct pages based on their need of a certain feature intuitively.

## Appetite

4 weeks

## Solution

https://www.notion.so/oursky/Improve-Authentication-Settings-UX-to-simplify-the-setup-and-prevent-unreasonable-settings-ea03155143f84d8b8daf73ebbed4c855

## Figma

https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=7451%3A188484

## Tasks

- [x] https://github.com/authgear/authgear-server/issues/2414
- [x] https://github.com/authgear/authgear-server/issues/2417
- [x] https://github.com/authgear/authgear-server/issues/2444
- [x] https://github.com/authgear/authgear-server/issues/2451
- [x] https://github.com/authgear/authgear-server/issues/2478
- [x] https://github.com/authgear/authgear-server/issues/2480

**Comment by fungc-io** [comment]
@louischan-oursky 
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=7653%3A114732

The copy and the design for custom state is updated
