### ISSUE TITLE
[Magic link] Login with email login links

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2748]
## Problem

To authenticate a user by possession of a mailbox, OTP is currently supported.
It's also common to send a link to the user which will magically log in the user.
While this method should works for both primary and secondary authenticators.
Support for secondary is priority as a requirement from the [client](https://3.basecamp.com/3096882/buckets/11477446/documents/5653990958)

## Solution

1. User receives an email with a login button
2. Redirected to the login screen hosted by Authgear, and logged in
3. User clicks on the "Continue" button
4. User is redirected via universal link to either the mobile app or a website.

(See Figma inside client project for details)

## Todo

- [ ] Update config file
- [ ] Backend support
- [ ] Email template
- [ ] SDK support
- [ ] Allow configuration in the portal 

---

- [x] #2764
- [x] #2773
- [x] #2765
    - Can refer to setup oob email
    - [x] Add menu item in /settings/mfa
- [ ] ~~#2766~~
    - Can refer to oob email
- [x] #2788
- [x] #2767
    - [x] Loading screen
	    - Can refer to wechat screen
	    - [x] Redirect on websocket event
- [x] #2768
    - [ ] Redirect on websocket event
    - [ ] Handle universal link
        Can refer to wechat's handling of universal link [docs.authgear.com/strategies/how-to-setup-sso-integrations/wechat](https://docs.authgear.com/strategies/how-to-setup-sso-integrations/wechat)
- [ ] ~~#2769~~
    - `authentication.primary.oob_otp_email_magic_link.failed`
    - `authentication.secondary.oob_otp_email_magic_link.failed`
- [x] #2770
- [x] #2771
    - [ ] Refactor to allow using unverfied authenticator
    - [ ] Implement createAuthenticator admin API mutation
- [ ] #2772

**Comment by fungc-io** [comment]
Update the original OOB-OTP for email to use magic link as alternative to code inside the email message

**Comment by fungc-io** [comment]
@IniZio 
Here are the updates on the design (re: [your comment](https://github.com/authgear/authgear-server/issues/2767#issuecomment-1383573202)) 
The UI is mostly good, please update the copywriting.


## Design

**Setup authenticator**

```markdown
## Set up login link 2-step verification

Input placeholder: Email address for receiving login links

[Next]
```

**Waiting for email verification**

```markdown
## Login link

We have sent a login link to xxx****@example.com
Please click on the link to continue

Didn't receive the link? [Resend (XXs)]
```

**Resend status**

```markdown
Login link successfully resent
```

**Login**

```markdown
## Login Link

We have sent a login link to xxx****@example.com
Please click on the link to continue

[ ] Do not ask again on this device

Didn't receive the link? [Resend (XXs)]

Having Trouble? [Use recovery code]

--- or ---

// list of alternative 2FA
```

 

**Email link verification**

**Email for verify magic link as new authenticator**

```markdown
Subject:
Verify your email for {AppName}

Body:
## Verify your email and setup 2-step verification on {AppName}

Please follow the link below to setup 2-step verification

[Verify email]

If you didn't trigger this setup, please ignore this email.
```

**Email for verify magic link to login**

```markdown
Subject:
Log in to {AppName}

Body:
## Use this link to sign in

Please follow the link below to sign in to {appName}. The link will expire in xx minutes and can only be use once.

[Sign in to {appName}]
```

**Approval Screen**

```markdown
## Confirm your login

Click the button to confirm login for {appName}

[Sign in]
```

**Success, close window screen**

```markdown
// no heading

You’re logged into {AppName}. Go back to the app.

You can close this window.
```

**Success at original session screen**

```markdown
## Login Link

(No change)
```

**Admin Panel**

```markdown
## Available 2-Factor

How can a user perform 2FA?

<list>
//...
[ ] OTP Code/Login Link via Email
</list>

...

// add pane above "Recovery Code", only show if "OTP Code/Login Link via Email" is checked in the list

## OTP Code/Login Link via Email

label: Verify email in 2FA by
dropdown: 
- OTP code
- Magic link

label: Skip email verification during setup
(toggle)
During setup of 2FA, users do not need to verify their email. Their email will be verified upon their next login.

## Recovery Code
...
```

Design of label -> toggle -> description for the portal for your reference (in application edit):

![image](https://user-images.githubusercontent.com/15207470/215261993-a88523c6-486a-49e4-a8c3-e39d78a0535f.png)

**Comment by fungc-io** [comment]
@IniZio Sorry I made a typo in the Admin Panel (Portal) part above.
It should be referred as "Login link", not "Magic link"

**Comment by IniZio** [comment]
@fungc-io Thanks I did correct it

**Comment by fungc-io** [comment]
Conclusion of discussion on 31 Jan:

- When magic link is turned on, OTP is still used as fallback
- Both the login link and OTP is sent to the user via email
- In the waiting screen in AuthUI, provide button for user to input OTP instead
- When either login link or OTP is used, the other one of the same session is invalidated
- No need provide affordance for user to verify their 2FA email in `/settings`

@IniZio

**Comment by IniZio** [comment]
Will be addressed in #2851

**Comment by fungc-io** [comment]
This feature is completed and the followup shall be addressed in https://github.com/authgear/authgear-server/issues/2851
