### ISSUE TITLE
[SDK WebView] New mode in SDKs to complete auth in WebView embedded in native apps

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2750]
Based on the POC issue created in the last cycle

- [x] #2774
- [x] authgear/authgear-sdk-ios#94
- [x] authgear/authgear-sdk-android#111
- [x] authgear/authgear-sdk-ios#95
- [x] authgear/authgear-sdk-android#112
