### ISSUE TITLE
Admin to change a user identity

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2778]
Currently the enduser can change their identity (email/phone number/username) via `/settings`

However it's not supported in Admin Portal and Admin API.

- Add a mutation to update identity
- Add affordance in portal
- The validation and duplication checking still applies

### Design:

Merge the buttons into a menu (https://fabricweb.z5.web.core.windows.net/oufr/8.104.2/#/examples/contextualmenu)

![image](https://user-images.githubusercontent.com/15207470/210925195-db0d2625-eaf6-492f-81a6-f9b4f899e521.png)

```
[ Actions 🔽 ]
[ Mark as verified/unverified ]
[ Edit ]
[ Remove ]
```

The edit page is similar to the "Add" page with the following changes:
![image](https://user-images.githubusercontent.com/15207470/210925132-73080744-c676-4bb4-9f68-eefcc348ec0a.png)

## Todo

- [x] Update action buttons to context menu
- [x] Add edit username screen
- [x] Add edit phone screen
- [x] Add edit email screen
- [x] Add mutation to update identity
- [x] Integrate update identity mutation
- [ ] Check new identity isVerified logic

**Comment by louischan-oursky** [comment]
No caveats.

**Comment by tung2744** [comment]
@fungc-io For oauth identity, we won't have edit right?

**Comment by fungc-io** [comment]
Only phone, email, username are editable

**Comment by tung2744** [comment]
- [x] Update action buttons to context menu
- [ ] Add edit username screen
- [ ] Add edit phone screen
- [ ] Add edit email screen
- [ ] Add mutation to update identity
- [ ] Integrate update identity mutation

**Comment by tung2744** [comment]
@carmenlau @louischan-oursky 
I found out the verified state is actually due to authenticator being created when new identity added. When I add an email identity, with password disabled, an oob_otp_email (Or oob_otp_sms if it is phone) authenticator will be created, and as a side effect it set the identity as verified. However, if password is enabled, this authenticator will not be created and therefore the identity becomes verified. Would like to confirm is this the expected behavoir?

**Comment by louischan-oursky** [comment]
No, creating OOB OTP authenticator via admin API should not mark the phone / email address as verified.

**Comment by tung2744** [comment]
ok. Then as a result new and edited identity will always be unverified.
