### ISSUE TITLE
[OTP] SMS OTP Limiting

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2780]
This are the new requirements for SMS OTP, details are written in each sub-issue.

### **Configurable Cooldown period**

- The current cooldown is set to 60s. Make it configurable per project so that user can choose 60s or 120s
- [x] https://github.com/authgear/authgear-server/issues/2781

### **Generate OTP on every resend**

- Regardless of the OTP valid lifetime, every resend should generate a new OTP. And the old one is immediately invalidated.
- [x] authgear/authgear-server#2782

### **Revoke current OTP after X attempts** 

- Let the default value of X be 5
- After 5 attempts of entering the OTP, the OTP is revoked and the enduser must generate a new one (resend) in order to continue
- The UI need to know there is no OTP available and block further input until the enduser triggers resending the OTP
- [x] authgear/authgear-server#2783

### **SMS send limit**

- There will be a daily send limit for each phone number. If the send limit is exceed the enduser cannot receive a new OTP until a day later. 
- Effectively this will block the user from logging in.
- [x] authgear/authgear-server#2784

**Comment by fungc-io** [comment]
@louischan-oursky Can you help do some technical planning on each sub-issue?
Thanks!

**Comment by louischan-oursky** [comment]
The shape of the new config

```
sms:
  ratelimit:
    per_phone:
      size: 20
      reset_period: 1day
    resend_cooldown_seconds: 60s
email:
  ratelimit:
    resend_cooldown_seconds: 60s
otp:
  ratelimit:
    failed_attempt:
      size: 5
      reset_period: 20min

```
