### ISSUE TITLE
Add tester app for trying out the login box

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3286]
## Todo

- Allow trigger "Try it out" from the portal
  - Serve a tester application at `[authgear-endpoint]/tester`
    - The tester app cannot trigger authentication by itself
    - The tester app offers a callback url to perform code exchange
    - It will show:
      - user info of the logged in enduser
      - a button to open the AuthUI Settings page
      - A button to go back to Authgear portal

---

- [ ] Always allow {authgear}/tester as a redirect uri.
- [x] Add a portal mutation, which on called, generates a token in redis `app:{app_id}:test:{token}`.
- [x] Add a "Try it out" out button, on triggers, call the above mutation, and navigate to `{authgear}/tester?token={generated_token}&portal_url={current_location}`
- [ ] Add a handler to handle `/tester`, which
    - [ ] If `token` exist in query, consume the token in redis. Redirect to authorization endpoint. Encode `portal_url` in `state`.
    - [ ] Else, if `code` exist in query, consumes `code` and display user info.
        - [ ] Display settings page button.
        - [ ] Display back to portal button, using `state.portal_url`.
    - [ ] Show an error if the above steps failed
    - [ ] Else, show a not found screen. (@fungc-io See what we want to show if someone enter `/tester` directly?)

**Comment by louischan-oursky** [comment]
1. I suggest we rename `portal_url` to `return_uri`.
2. We only allow `return_uri` to begin with the portal origin (configured in environment variable), and with a path prefix of the same project (i.e. `/project/{encoded_project_id}`). This mitigates open redirection.
3. What client_id is used in this flow? `client_id=` (the empty client id?) Maybe we should specify when `client_id=`, a synthetic client is used, the only redirect_uri is `origin/tester`.

**Comment by tung2744** [comment]
@fungc-io Will there be a design for the "tester" screen?

**Comment by tung2744** [comment]
@louischan-oursky After some thought, I think we can simply store `return_uri` with the test token in redis, so it cannot be changed by the query, and don't have to worry about whitelisting.

**Comment by fungc-io** [comment]
@tung2744 sorry let me draft one today

**Comment by fungc-io** [comment]
@tung2744 Let's use this notion page for the design:

https://www.notion.so/oursky/Login-Success-5c3074df9107422f95f75354ac748015?pvs=4

Like this:
<img width="1068" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/14e862cb-a968-4fba-81cd-9e52c3f61565">

**Comment by fungc-io** [comment]
checked ok
