### ISSUE TITLE
[SDK] Introduce getOrRefreshAccessToken and deprecate refreshAccessTokenIfNeeded

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3655]
## Problem

- The original function in SDK "refreshAccessTokenIfNeeded" has a confusing name and not easy to understand behavior

## Appetite

2 week

## Solution

- Introduce new function "getOrRefreshAccessToken" and mark "refreshAccessTokenIfNeeded" deprecated in the SDK for each platform
- The new function should always either return a valid access token, or throw an exception
- It should return promise or string depends on the platform convention. e.g. JavaScript, a promise. On Android a callback class. On iOS a completion handler.
- Error handling in doc: 
  - The new API references and docs should make it simple for developers users to reference all of the exception cases. Including:
    - IOException, or
    - Users is not logged in, or 
    - refresh tokens not exists etc.

## Todo

- Update SDK
  - [ ] iOS
  - [ ] Android
  - [ ] JS
    - [ ] Web
    - [ ] RN
    - [ ] Capacitor
  - [ ] Flutter
  - [ ] Xamarin
- [ ] Update Tutorial
  - [ ] Replace all refreshAccessTokenIfNeeded usage with getOrRefreshAccessToken
  - [ ] Make sure all exception cases are described in the API references for all platforms
  - [ ] Link the doc to the exception cases for all platforms
