### ISSUE TITLE
Roles and Groups configuration in Portal

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3867]
## Goal

* In Portal, under "User Management", there will be 2 new pages, "Roles" and "Groups"
* User can set up the roles and groups and assign users into them in these 2 new pages

Main issue: #3537

## Design

[https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=5%3A29&mode=dev&t=OMQOdo4krATncTFn-1](https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=5%3A29&mode=dev&t=OMQOdo4krATncTFn-1)

## Todo

- [ ] Api integration
- [ ] Configure route of roles and groups in portal
- [ ] Role
  - [ ] Empty State
  - [ ] Create Role Form
  - [ ] Role List View
    - [ ] list item
    - [ ] search bar (by name and key)
    - [ ] pagination
  - [ ] Role Detail Page
    - [ ] setting tab
    - [ ] groups tab
      - [ ] empty state
      - [ ] groups list view
      - [ ] search bar
      - [ ] add to group dialog
        - [ ] combobox
      - [ ] remove group dialog
    - [ ] users tab
      - [ ] empty state
      - [ ] users list view
      - [ ] search bar
      - [ ] add to user dialog
        - [ ] combobox
      - [ ] remove user dialog
  - [ ] Delete Role
- [ ] Group
  - [ ] Empty State
  - [ ] Create Group Form
  - [ ] Group List View
    - [ ] list item
    - [ ] search bar (by name and key)
    - [ ] pagination
  - [ ] Group Detail Page
    - [ ] setting tab
    - [ ] roles tab
      - [ ] empty state
      - [ ] roles list view
      - [ ] search bar
      - [ ] add to role dialog
        - [ ] combobox
      - [ ] remove role dialog
    - [ ] users tab
      - [ ] empty state
      - [ ] users list view
      - [ ] search bar
      - [ ] add to user dialog
        - [ ] combobox
      - [ ] remove user dialog
  - [ ] Delete Group

**Comment by fungc-io** [comment]
Hi @ngkaokis,

You can find the design in this figma file: 

[https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=5%3A29&mode=dev&t=OMQOdo4krATncTFn-1](https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=5%3A29&mode=dev&t=OMQOdo4krATncTFn-1)

Please help plan the tasks and give estimations for this implementation.

**Comment by fungc-io** [comment]
Based on our discussion today, 

1. When creating roles and groups, "Name" goes before "Key"
   1. In Roles, the user needs to input the name and key separately
   2. In Groups, the "Key" placeholder is a converted "Name", if key is not provided, it used the prefilled value.
2. Remove "User Tab" from scope of this cycle
