### ISSUE TITLE
UI issues of Authgear Setting page

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#914]
Here are a list of issues at Authgear Setting page (`/settings`)

- At `/settings`
  - [x] Move "Click here to sign up" from the top to bottom with "Log out"
  - [x] After click the Log out, display "Confirm if you really want to logout" "Confirm" (actually why need a separate page for this? Can we just logout directly?)
- At `/settings/mfa`
  - [x] If listing recovery code is disabled by administrator, don't display the "Recover Code option" #930 
  - [x] "Forget all trusted devices" => "Forgot all trusted devices that could skip MFA", and give a feedback when this button is clicked.
  - [x] When there are no MFA configured, change "Details" to "Configure" #860 
- At `enter_oob_otp`
  - [x] It seems timeout are now displayed as "network error", can we distinguish it and display a more relevant error? #933
  - [x] The "Didn't receive the code?" text size is abnormal (should be same or smaller then content font size)
  - [x] The "Resend" text countdown is grey and impossible to read.

~~BTW, when using MFA, the back button fail, I can't find the pattern yet; But at least I know it ALWAYS fail after I setup a new TOTP authenticator, the last back button will fail.~~ Will be handled in issue #924

**Comment by carmenlau** [comment]
> Remove the "Forget all trusted devices"? What's it for?

When user login with totp mfa, we should have a checkbox for the user to check if they want to trust the device. A device token will be stored in the device and next time when the user login, they will not need to perform totp auth in the same device. The "trusted devices" is refer to this feature, let me check the functionalities when we work on this issue.

**Comment by chpapa** [comment]
@carmenlau thanks, I updated the actionable item to:

"Forget all trusted devices" => "Forgot all trusted devices that could skip MFA", and give a feedback when this button is clicked.

**Comment by carmenlau** [comment]
> After click the Log out, display "Confirm if you really want to logout" "Confirm" (actually why need a separate page for this? Can we just logout directly?)

As I remember it is intended, but cannot recall the reason. Do you know why? @kiootic 

> If listing recovery code is disabled by administrator, don't display the "Recover Code option"

I found there is a "get new code" button in the recovery page. So currently if admin disabled listing, user cannot list the existing code, but they can get the new one. Maybe we should keep the option there but change the copywriting? Or user should not be able to get new code in this case?

<img width="712" alt="Screenshot 2021-01-27 at 3 41 31 PM" src="https://user-images.githubusercontent.com/388892/105944075-b14f2300-60b6-11eb-9bea-8836832989d6.png">

> It seems timeout are now displayed as "network error", can we distinguish it and display a more relevant error?

May I know how you get this error? When trigger sending email or sms? I understand that timeout should be something random 🙈 See if there is more hints that I can check.

> BTW, when using MFA, the back button fail, I can't find the pattern yet; But at least I know it ALWAYS fail after I setup a new TOTP authenticator, the last back button will fail.

The back button is history back. It seems that this is general auth flow redirection problem, not specific to mfa. When a interaction completed (e.g. Signup flow, login flow, setup mfa), click the back button try to go back to previous page, but the interaction is completed so you will see "This page has expired" page. Will check how to fix it.

**Comment by kiootic** [comment]
> After click the Log out, display "Confirm if you really want to logout" "Confirm" (actually why need a separate page for this? Can we just logout directly?)

The logout page is intended to be directly linkable from outside Authgear, so we need to ask user to confirm log out.

**Comment by chpapa** [comment]
> I found there is a "get new code" button in the recovery page. So currently if admin disabled listing, user cannot list the existing code, but they can get the new one. Maybe we should keep the option there but change the copywriting? Or user should not be able to get new code in this case?

I think instead of change the copywriting, we should just make a link directly in the setting page say "get new code".

So is that we have 3 permissions?
1. Can't list old code, can't get new code
2. Can't list old code, can get new code
3. Can get old code / regenerate new code.

Actually what is the security best practices...? We should pick a default, or even just support the default.

> May I know how you get this error? When trigger sending email or sms? I understand that timeout should be something random 🙈 See if there is more hints that I can check.

Umm, I get it twice when I leave the enter otp open for quite some time, and when I put the code in again, it will show the "network error"

> The logout page is intended to be directly linkable from outside Authgear, so we need to ask user to confirm log out.

I think maybe a better way is we have a logout page that's intended to be linkable, but for the logout link on the setting page we logout directly?

**Comment by carmenlau** [comment]
> So is that we have 3 permissions?

No, we only have `list_enabled` option.

Should we add `regenerate_enabled`? To be more secure, both of them should be disabled by default? If `regenerate_enabled` is disabled, the only way to recover the account if user lost both totp and recovery code, is to ask account to help him to remove the authenticator in portal.

> The logout page is intended to be directly linkable from outside Authgear, so we need to ask user to confirm log out.

> I think maybe a better way is we have a logout page that's intended to be linkable, but for the logout link on the setting page we logout directly?

Agree that if the intention is for linkable from outside Authgear, we can logout directly from the setting page.

**Comment by carmenlau** [comment]
@chpapa Would like to clarify one more thing.

> When there are no MFA configured, change "Details" to "Configure"

I thought we only need to change the word. But if i recall correctly, we discussed about it the "Configure" button should behave differently, it should skip the empty list and go to the add page correspondingly? Seems it is better in UX. And I found this issue https://github.com/authgear/authgear-server/issues/860

**Comment by chpapa** [comment]
> No, we only have list_enabled option. Should we add regenerate_enabled? To be more secure, both of them should be disabled by default?

I think we can keep the changes minimal. Keep `list_enabled` only (or rename it to `list_regenerate_enabled`), if it is `true` then we display the recovery code option in setting page, users can list code and generate new code; if `false` then we hide it and both list/regenerate is disabled.

Default could be false. (But true is also not so bad I guess? At least I know Google can do that)

> I thought we only need to change the word. But if i recall correctly, we discussed about it the "Configure" button should behave differently, it should skip the empty list and go to the add page correspondingly? Seems it is better in UX. And I found this issue #860

Yes, sorry I didn't notice #860 and should have been more specific.
