### ISSUE TITLE
[Portal, Appearance] Banner and SSO buttons configuration

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#941]
- [x] [Move Appearance into its own tab](https://github.com/authgear/authgear-server/issues/1016)
- [x] [Revamp language widget](https://github.com/authgear/authgear-server/issues/1021)
- [x] [Add shorthand for app name, privacy policy link, terms of service link, default uris](https://github.com/authgear/authgear-server/issues/1030)
- [ ] [Enhance logo configuration](https://github.com/authgear/authgear-server/issues/1033)

---

> The following is the original description

---

- Full width
- Fixed Height

![image](https://user-images.githubusercontent.com/16920209/106999008-645b0300-67c0-11eb-8f8b-20a05b04aeb1.png)

**Width and Height Option**

- SSO button shape
![image](https://user-images.githubusercontent.com/16920209/106422789-2eeda700-649a-11eb-8aa6-6165ea704341.png)

**Comment by chpapa** [comment]
On the design, I think left right / top bottom padding should use an input box instead of slider for percentage, it is just not convenient for developers.

**Comment by mr9dollars** [comment]
https://github.com/authgear/authgear-server/issues/966

Can we also support dark mode banner configuration in this issue? @louischan-oursky
