### ISSUE TITLE
Biometric authentication for mobile apps

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#943]
- [x] Add biometric identity data model (https://github.com/authgear/authgear-server/issues/1074)
- [x] Skip MFA for OAuth identity and biometric identity. (https://github.com/authgear/authgear-server/issues/1074)
- [x] Enforce the invariant that `A user must have at least one Login ID identity or OAuth identity`. (https://github.com/authgear/authgear-server/issues/1074)
- [x] `/oauth2/challenge` (https://github.com/authgear/authgear-server/issues/1079)
- [x] `/oauth2/token` (https://github.com/authgear/authgear-server/issues/1079)
  - [x] `action = setup`: require `jwt` and `device_info`
  - [x] `action = authenticate`
- [x] Show biometric identity in settings page (https://github.com/authgear/authgear-server/issues/1086)
- [x] Make sure anonymous user cannot setup biometric
- [x] Show device info (https://github.com/authgear/authgear-server/issues/1094)
- [x] Show biometric identity in portal (https://github.com/authgear/authgear-server/issues/1099)
- [x] SDK remove dependency on react-native-async-storage (https://github.com/authgear/authgear-sdk-js/issues/68)
- [x] SDK biometric APIs (https://github.com/authgear/authgear-sdk-ios/issues/49, https://github.com/authgear/authgear-sdk-android/issues/61, https://github.com/authgear/authgear-sdk-js/issues/66)
