### ISSUE TITLE
UX Enhancement Tracking

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#966]
List some relatively important UX enhancement issues here so someone can try to fix in one go.

Portal
* [ ] #901 Re-org of Portal Navigation
* [ ] #965 More email templates
* [x] #961 Color picker displaced
* [ ] #915 Improve Portal Collaborator Invitation
* [ ] #912 Allow download admin api jwk from portal.
* [x] #945 Custom public domain feature UX improvement
* [x] Replace the reset icon of bin to something like an undo button: 
![d427797a033af24359c8af6012729747](https://user-images.githubusercontent.com/387241/107015762-181bbd00-67d8-11eb-8d4e-fa3bee378e17.png)
* [x] Update Users > User Details > Identities, change verify and unverify buttons to mark as verified.
* [x] #987 In Authentication > Login ID,  Add explanation to email login id options

Auth UI
* [x] #953 Verification code expired UX enhancement
* [x] #952 User sign up username / email field should display correct placeholder 
* [x] #940 Keyboard Navigation
* [x] #916 Password Manager support
* [x] #939 Update error display UI
* [x] #938 Enhancement for login and register
* [ ] #972 Add anchor to go back to login page after forget password
* [x] #1003 Support different logo in dark mode?

**Comment by chpapa** [comment]
Closing since most are either fixed or obsoleted.
